# Generated by Django 3.1.5 on 2021-01-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=60)),
                ('answer_value', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Таблица ответов',
                'verbose_name_plural': 'Таблица ответов',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('end_date', models.DateField()),
                ('slug', models.SlugField(max_length=120)),
                ('form_id', models.CharField(max_length=60)),
                ('qr_image', models.ImageField(upload_to='qrs', verbose_name='QR')),
            ],
            options={
                'verbose_name': 'Таблица форм',
                'verbose_name_plural': 'Таблица форм',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('answer_field', models.ManyToManyField(to='create_form.Answer')),
            ],
            options={
                'verbose_name': 'Таблица вопросов',
                'verbose_name_plural': 'Таблица вопросов',
            },
        ),
        migrations.CreateModel(
            name='FormSended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50)),
                ('answers', models.ManyToManyField(to='create_form.Answer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.form')),
            ],
            options={
                'verbose_name': 'Таблица заполненных форм',
                'verbose_name_plural': 'Таблица заполненных форм',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(to='create_form.Question'),
        ),
    ]
