# Generated by Django 3.1.5 on 2021-01-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0002_auto_20210124_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=50),
        ),
    ]
