# Generated by Django 3.1.5 on 2021-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0003_auto_20210124_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='qr_image',
            field=models.ImageField(upload_to='qrs/', verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.CharField(max_length=120),
        ),
    ]
