# Generated by Django 3.1.5 on 2021-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0005_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'ответы', 'verbose_name_plural': 'Таблица ответов'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'комментарии', 'verbose_name_plural': 'Таблица коментариев'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'формы', 'verbose_name_plural': 'Таблица форм'},
        ),
        migrations.AlterModelOptions(
            name='formsended',
            options={'verbose_name': 'заполненные формы', 'verbose_name_plural': 'Таблица заполненных форм'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопросы', 'verbose_name_plural': 'Таблица вопросов'},
        ),
        migrations.AddField(
            model_name='form',
            name='password',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
