# Generated by Django 3.1.5 on 2021-01-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0008_comments_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='report_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='create_form.formsended'),
        ),
    ]
