# Generated by Django 3.1.7 on 2021-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0010_auto_20210130_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=60)),
                ('answer_value', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='sub_answer',
            field=models.ManyToManyField(blank=True, to='create_form.SubAnswer'),
        ),
    ]
