# Generated by Django 3.1.7 on 2021-03-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0011_auto_20210322_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAnswerChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.answer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_form.form')),
                ('sub_answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_form.subanswer')),
            ],
        ),
    ]
