# Generated by Django 3.1.7 on 2021-03-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0012_subanswerchosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subanswerchosen',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_form.formsended'),
        ),
    ]
