# Generated by Django 3.1.7 on 2021-03-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0013_auto_20210323_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_form.question'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_form.formsended'),
        ),
        migrations.AlterField(
            model_name='formsended',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_form.form'),
        ),
        migrations.AlterField(
            model_name='subanswerchosen',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_form.answer'),
        ),
    ]
