# Generated by Django 3.1.5 on 2021-03-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0014_auto_20210324_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=300),
        ),
    ]
