# Generated by Django 3.1.5 on 2021-03-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0016_auto_20210326_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
