# Generated by Django 3.2 on 2021-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0017_auto_20210326_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='subanswer',
            name='answer_id',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='subanswer',
            name='answer_value',
            field=models.CharField(max_length=160),
        ),
    ]
