# Generated by Django 3.2 on 2021-04-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0018_auto_20210423_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.question'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.formsended'),
        ),
        migrations.AlterField(
            model_name='formsended',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.form'),
        ),
        migrations.AlterField(
            model_name='subanswerchosen',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.answer'),
        ),
        migrations.AlterField(
            model_name='subanswerchosen',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.formsended'),
        ),
        migrations.AlterField(
            model_name='subanswerchosen',
            name='sub_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_form.subanswer'),
        ),
    ]
