# Generated by Django 3.2 on 2021-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0019_auto_20210423_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subanswer',
            options={'verbose_name': 'Связанные ответы', 'verbose_name_plural': 'Таблица связанных ответов'},
        ),
        migrations.AlterModelOptions(
            name='subanswerchosen',
            options={'verbose_name': 'Выбранные связанные ответы пользователями', 'verbose_name_plural': 'Таблица выбранных связанных ответов'},
        ),
        migrations.AlterField(
            model_name='form',
            name='form_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя формы'),
        ),
    ]
