# Generated by Django 3.2.3 on 2021-05-28 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0022_auto_20210423_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsended',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
